### DISCUSSION TITLE
Proposal for an extended wind sensor

### DISCUSSION THREAD

**Discussion by coasting24** [damianeickhoff/HaCasa#24] [Ideas]
View:

```
      - type: custom:button-card
        template: custom_card_weather_sensor_wide
        entity: sensor.wettervorhersage_oldschool_entitat
        name: "[[[ return 'Wind ' + states['sensor.windrichtung'].state ]]]"
        variables:
          hc_card_weather_sensor_background: #var(--color-gold)
          hc_card_weather_sensor_icon: mdi:weather-windy
          hc_card_weather_sensor_1: "[[[ return states[ entity.entity_id ].attributes.forecast[0].wind_speed ]]]"
          hc_card_weather_sensor_2: "[[[ return states[ entity.entity_id ].attributes.forecast[0].wind_gust_speed ]]]"
          hc_card_weather_sensor_3: #"[[[ return states['sensor.windrichtung'].state ]]]"
          hc_card_weather_sensor_unit: km/h

```

Template:

```
custom_card_weather_sensor_wide:
  variables:
    hc_card_weather_sensor_background:
    hc_card_weather_sensor_icon: 
    hc_card_weather_sensor_1:
    hc_card_weather_sensor_2:
    hc_card_weather_sensor_3:
    hc_card_weather_sensor_unit:
  triggers_update:
    - "[[[ return variables.hc_card_weather_sensor_1 ]]]"
    - "[[[ return variables.hc_card_weather_sensor_2 ]]]"
    - "[[[ return variables.hc_card_weather_sensor_3 ]]]"    
  show_icon: true
  icon: '[[[ return variables.hc_card_weather_sensor_icon ]]]'
  show_state: false
  name: '[[[ return variables.hc_card_weather_sensor_1 ]]]'
  aspect_ratio: 2/1
  tap_action:
    action: more-info
  styles:
    card:
      - background: '[[[ return variables.hc_card_weather_sensor_background ]]]'
      - padding: 15px
    grid:
      - grid-template-areas: '"i n n" "row_1 row_1 image" "row_2 row_2 image" '
      - grid-template-columns: min-content 1fr 1fr
      - grid-template-rows: min-content min-content min-content
      - row-gap: 0.8rem
      - column-gap: 0.8rem
    icon:
      - width: 100%
      - padding: 0
      - color: var(--color-gold)
      - opacity: 0.8
    img_cell:
      - width: 1rem
      - height: 1.5rem
      - padding: 0
    name:
      - font-size: 0.9rem
      - color: var(--color-gold)
      - justify-self: start
      - opacity: 0.8
      - font-weight: 400
      - font-family: montserrat
    custom_fields:
      row_1:
        - justify-self: start
        - align-self: start
      row_2:
        - justify-self: start
        - align-self: start
      image:
        - justify-self: start
        - align-self: start
  
  custom_fields:
    row_1:
      card:
        type: custom:button-card
        name: '[[[ return variables.hc_card_weather_sensor_1 ]]]'
        label: |
          [[[
            return `<span style='color: var(--text);'>${variables.hc_card_weather_sensor_unit}</span><br><span style='color: var(--color-gold);'>Wind Speed</span>`
          ]]]
        show_label: true
        styles:
          grid:
            - grid-template-areas: '"n l"'
            - grid-template-rows: 1fr
          name:
            - padding: 0 0 0 0
            - margin: 0 0 0 0
            - font-size: 2.5rem
            - font-family: montserrat
            - font-weight: 600
            - justify-self: start
            - align-self: start
          label:
            - justify-self: start
            - align-self: center
            - text-align: start
            - padding-left: 5px
            - font-size: 0.9rem
          card:
            - background: none
            - box-shadow: none
    row_2:
      card:
        type: custom:button-card
        name: '[[[ return variables.hc_card_weather_sensor_2 ]]]'
        label: |
          [[[
            return `<span text-align: start style='color: var(--text);'>${variables.hc_card_weather_sensor_unit}</span><br><span style='color: var(--color-gold);'>Wind Gust Speed</span>`
          ]]]
        show_label: true
        styles:
          grid:
            - grid-template-areas: '"n l"'
            - grid-template-rows: min-content
          name:
            - padding: 0 0 0 0
            - margin: 0 0 0 0
            - font-size: 2.5rem
            - font-family: montserrat
            - font-weight: 600
            - justify-self: start
            - align-self: start
          label:
            - justify-self: start
            - align-self: center
            - text-align: start
            - padding-left: 5px
            - font-size: 0.9rem
          card:
            - background: none
            - box-shadow: none
    image: >
      [[[
        var bearing = states['weather.home'].attributes.wind_bearing;
        return `
          <svg width="60%" height="60%" viewBox="0 0 1952 1952" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
            <g id="Layer1">
              <path id="Circle" fill="var(--color-gold)" d="M975.913,0c538.62,0 975.912,437.292 975.912,975.913c0,538.62 -437.292,975.912 -975.913,975.912c-538.62,0 -975.912,-437.292 -975.912,-975.913c0,-538.62 437.292,-975.912 975.913,-975.912Zm-0,208.546c423.52,-0 767.366,343.846 767.366,767.367c0,423.52 -343.846,767.366 -767.367,767.366c-423.52,0 -767.366,-343.846 -767.366,-767.367c-0,-423.52 343.846,-767.366 767.367,-767.366Z"/>
              <path id="Direction" fill="var(--color-gold)" transform="rotate(` + bearing + ` 976 976)" d="M975.915,1560.9l332.229,-1169.98l-339.429,122.592l-325.034,-122.592l332.234,1169.98Z"/>
                <animateTransform additive="sum" attributeName="transform" calcMode="spline" dur="2s" keySplines=".42, 0, .58, 1; .42, 0, .58, 1" repeatCount="indefinite" type="rotate" values="0 976 976; 5 976 976; 0 976 976" />    
            </g>
          </svg>
        `;
      ]]]

    # alternative version
    image_2: >
      [[[
        var bearing = states['weather.home'].attributes.wind_bearing;
        var cardinal = states['sensor.windrichtung'].state; 
        return `
          <svg width="90%" height="90%" viewBox="0 0 2000 2000" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;">
            <g id="Layer1">
              <g id="Marker"><path d="M287.635,1123.96l82.345,-0" style="fill:none;stroke:var(--color-gold);stroke-width:16.67px;"/>
                <path d="M400.541,706.972l71.313,41.173" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M1777.9,1501.94l70.408,42.702" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M398.861,1541.73l71.402,-41.018" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M1778.34,748.369l71.031,-41.657" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M706.716,400.394l41.4,71.181" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M1504.37,1777.08l39.854,72.059" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M1542.19,401.302l-41.066,71.374" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M749.262,1779.84l-42.597,70.472" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
                <path d="M1126.07,285.909l-52.693,92.696l109.369,0.072l-56.676,-92.768Z" style="stroke:var(--color-gold);stroke-width:2.08px;"/>
                <path d="M1879.93,1123.96l82.437,-0" style="fill:none;stroke:var(--color-gold);stroke-width:16.67px;"/>
                <path d="M1125.38,1964.09l-0,-82.703" style="fill:none;stroke:var(--color-gold);stroke-width:16.67px;"/>
              </g>
              <g id="NESW">
                <g transform="matrix(191.667,0,0,191.667,1210.38,560.357)"></g>
                  <text x="1055.51px" y="560.357px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">N</text>
                <g transform="matrix(191.667,0,0,191.667,1832.45,1188.08)"></g>
                  <text x="1703.84px" y="1188.09px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">E</text>
                <g transform="matrix(191.667,0,0,191.667,1192.38,1809.29)"></g>
                  <text x="1070.1px" y="1809.3px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">S</text>
                <g transform="matrix(191.667,0,0,191.667,630.031,1188.08)"></g>
                  <text x="407.123px" y="1188.09px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">W</text>
              </g>
              <g id="Bearing" transform="rotate(` + bearing + ` 1125 1125)">
                <g><path d="M1137.54,340.861l0.146,294.307l-24.794,1.592c-0,0 -2.052,-246.606 -2.463,-295.928c0,0 0.122,0.2 0,0" style="fill:var(--color-gold);stroke-width:2.08px;" />
                  <path d="M1156.99,330.877c-25.849,18.327 -61.714,12.22 -80.041,-13.629c-18.327,-25.849 -12.22,-61.714 13.63,-80.041c25.849,-18.327 61.714,-12.219 80.04,13.63c18.327,25.849 12.22,61.714 -13.629,80.04Zm-16.603,-23.417c-12.925,9.163 -30.857,6.11 -40.02,-6.815c-9.164,-12.924 -6.11,-30.857 6.814,-40.02c12.925,-9.164 30.857,-6.11 40.021,6.814c9.163,12.925 6.109,30.858 -6.815,40.021Z" style="fill:var(--color-gold);stroke-width:2.27px;"/>
                </g>
                  <path d="M1124.83,1985.4l69.828,-147.314l-55.777,34.667l-3.626,-295.232l-25.323,0.2l-1.847,291.762l-52.894,-24.77l69.639,140.687Z" style="fill:var(--color-gold);stroke-width:2.08px;"/>
                    <animateTransform additive="sum" attributeName="transform" calcMode="spline" dur="2s" keySplines=".42, 0, .58, 1; .42, 0, .58, 1" repeatCount="indefinite" type="rotate" values="0 1125 1125; 5 1125 1125; 0 1125 1125" />    
                </g>
              <g id="Cardinal" ></g>
                <text x="57%" y="57%" dominant-baseline="middle" text-anchor="middle" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:250px;">`+ cardinal + `</tspan></text>
            </g>
          </svg>
        `;
      ]]]
```

**Comment by Scatman007** [comment]
Tried this, but my arrow is always pointing in the opposite direction.
Any idea how to fix this? Also with the alternative version.

**Reply by coasting24** [reply]
Hmm... can you confirm that your weather provider is giving you the direction the wind is coming from?  
-> means the wind is coming from west
<- means wind is coming from east

**Comment by coasting24** [comment]
BTW. I have made some changes since July and the new code now looks like this:

View:
```
      - type: custom:button-card
        template: custom_card_weather_wind
        entity: sensor.wettervorhersage_oldschool_entitat
        name: |
          [[[ return 'Wind ' + states['sensor.windrichtung'].state ]]]
        variables:
          hc_card_weather_wind_background: #var(--color-gold)
          hc_card_weather_wind_icon: mdi:weather-windy
          hc_card_weather_wind_1: |
            [[[ return states[ entity.entity_id ].attributes.forecast[0].wind_speed ]]]
          hc_card_weather_wind_2: |
            [[[ return states[ entity.entity_id ].attributes.forecast[0].wind_gust_speed ]]]
          hc_card_weather_wind_bearing: |
            [[[ return states['weather.home'].attributes.wind_bearing ]]]
          hc_card_weather_wind_unit: "km/h"
```
Template:

```
---
### Custom Card Wind ###
custom_card_weather_wind:
  variables:
    hc_card_weather_wind_1:  # wind speed
    hc_card_weather_wind_2:  # wind gust speed
    hc_card_weather_wind_bearing: # wind bearing 0-360°
    hc_card_weather_wind_background: # background color
    hc_card_weather_wind_icon: # icon to show
    hc_card_weather_wind_unit: "km/h"
  triggers_update:
    - "[[[ return variables.hc_card_weather_wind_1 ]]]"
    - "[[[ return variables.hc_card_weather_wind_2 ]]]"
    - "[[[ return variables.hc_card_weather_wind_bearing ]]]"
  show_icon: true
  icon: '[[[ return variables.hc_card_weather_wind_icon ]]]'
  show_state: false
  name: '[[[ return variables.hc_card_weather_wind_1 ]]]'
  aspect_ratio: 2/1
  tap_action:
    action: more-info
  styles:
    card:
      - background: '[[[ return variables.hc_card_weather_wind_background ]]]'
      - padding: 15px
      - height: 90%

    grid:
      - grid-template-areas: '"i n n" "row_1 row_1 image" "row_2 row_2 image" '
      - grid-template-columns: min-content 1fr 1fr
      - grid-template-rows: min-content min-content min-content
      - row-gap: 0.8rem
      - column-gap: 0.8rem
    icon:
      - width: 100%
      - padding: 0
      - color: var(--color-gold)
      - opacity: 0.8
    img_cell:
      - width: 1rem
      - height: 1.5rem
      - padding: 0
      - justify-self: start
    name:
      - font-size: 0.9rem
      - color: var(--color-gold)
      - justify-self: start
      - opacity: 0.8
      - font-weight: 400
      - font-family: montserrat
    custom_fields:
      row_1:
        - justify-self: start
        - align-self: start
      row_2:
        - justify-self: start
        - align-self: start
      image:
        - justify-self: start
        - align-self: start
  
  custom_fields:
    row_1:
      card:
        type: custom:button-card
        name: '[[[ return variables.hc_card_weather_wind_1 ]]]'
        label: |
          [[[
            return `<span style='color: var(--text);'>${variables.hc_card_weather_wind_unit}</span><br><span style='color: var(--color-gold);'>Wind Speed</span>`
          ]]]
        show_label: true
        styles:
          grid:
            - grid-template-areas: '"n l"'
            - grid-template-rows: min-content
          name:
            - padding: 0 0 0 0
            - margin: 0 0 0 0
            - font-size: 2.5rem
            - font-family: montserrat
            - font-weight: 600
            - justify-self: start
            - align-self: start
          label:
            - justify-self: start
            - align-self: center
            - text-align: start
            - padding-left: 5px
            - font-size: 0.9rem
          card:
            - background: none
            - box-shadow: none
    row_2:
      card:
        type: custom:button-card
        name: '[[[ return variables.hc_card_weather_wind_2 ]]]'
        label: |
          [[[
            return `<span text-align: start style='color: var(--text);'>${variables.hc_card_weather_wind_unit}</span><br><span style='color: var(--color-gold);'>Wind Gust Speed</span>`
          ]]]
        show_label: true
        styles:
          grid:
            - grid-template-areas: '"n l"'
            - grid-template-rows: min-content
          name:
            - padding: 0 0 0 0
            - margin: 0 0 0 0
            - font-size: 2.5rem
            - font-family: montserrat
            - font-weight: 600
            - justify-self: start
            - align-self: start
          label:
            - justify-self: start
            - align-self: center
            - text-align: start
            - padding-left: 5px
            - font-size: 0.9rem
          card:
            - background: none
            - box-shadow: none
#    image: >
#      [[[
#        var bearing = states['weather.home'].attributes.wind_bearing;
#        return `
#          <svg width="60%" height="60%" viewBox="0 0 1952 1952" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
#            <g id="Layer1">
#              <path id="Circle" fill="var(--color-gold)" d="M975.913,0c538.62,0 975.912,437.292 975.912,975.913c0,538.62 -437.292,975.912 -975.913,975.912c-538.62,0 -975.912,-437.292 -975.912,-975.913c0,-538.62 437.292,-975.912 975.913,-975.912Zm-0,208.546c423.52,-0 767.366,343.846 767.366,767.367c0,423.52 -343.846,767.366 -767.367,767.366c-423.52,0 -767.366,-343.846 -767.366,-767.367c-0,-423.52 343.846,-767.366 767.367,-767.366Z"/>
#              <path id="Direction" fill="var(--color-gold)" transform="rotate(` + bearing + ` 976 976)" d="M975.915,1560.9l332.229,-1169.98l-339.429,122.592l-325.034,-122.592l332.234,1169.98Z"/>
#                <animateTransform additive="sum" attributeName="transform" calcMode="spline" dur="2s" keySplines=".42, 0, .58, 1; .42, 0, .58, 1" repeatCount="indefinite" type="rotate" values="0 976 976; 5 976 976; 0 976 976" />    
#            </g>
#          </svg>
#        `;
#      ]]]

    image: >
      [[[
        // states['weather.home'].attributes.wind_bearing;
        var bearing = variables.hc_card_weather_wind_bearing; 
        return `
          <svg width="70%" height="70%" viewBox="0 0 512 512" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
            <g id="Group">
              <path id="Circle" fill="var(--color-gold)" d="M256,-0c141.29,-0 256,114.71 256,256c0,141.29 -114.71,256 -256,256c-141.29,-0 -256,-114.71 -256,-256c0,-141.29 114.71,-256 256,-256Zm0,40.96c118.684,0 215.04,96.356 215.04,215.04c-0,118.684 -96.356,215.04 -215.04,215.04c-118.684,-0 -215.04,-96.356 -215.04,-215.04c0,-118.684 96.356,-215.04 215.04,-215.04Z"/>
              <path id="Direction" fill="var(--color-gold)" transform="rotate(` + bearing + ` 256 256)" d="M352.217,140.698l-80.177,253.716c-6.425,20.347 -25.647,20.347 -32.084,0l-80.177,-253.716c-7.264,-22.974 8.865,-35.785 23.981,-24.398l64.299,70.995c4.999,3.765 10.89,3.765 15.878,-0l64.299,-70.995c15.116,-11.372 31.256,1.409 23.981,24.398">
                <animateTransform additive="sum" attributeName="transform" calcMode="spline" dur="2s" keySplines=".42, 0, .58, 1; .42, 0, .58, 1" repeatCount="indefinite" type="rotate" values="0 256 256; 5 256 256; 0 256 256" />    
              </path>  
            </g>
          </svg>
        `;
      ]]]

    # alternative version
#    image: >
#      [[[
#        var bearing = states['weather.home'].attributes.wind_bearing;
#        var cardinal = states['sensor.windrichtung'].state; 
#        return `
#          <svg width="90%" height="90%" viewBox="0 0 2000 2000" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;">
#            <g id="Layer1">
#              <g id="Marker"><path d="M287.635,1123.96l82.345,-0" style="fill:none;stroke:var(--color-gold);stroke-width:16.67px;"/>
#                <path d="M400.541,706.972l71.313,41.173" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M1777.9,1501.94l70.408,42.702" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M398.861,1541.73l71.402,-41.018" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M1778.34,748.369l71.031,-41.657" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M706.716,400.394l41.4,71.181" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M1504.37,1777.08l39.854,72.059" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M1542.19,401.302l-41.066,71.374" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M749.262,1779.84l-42.597,70.472" style="fill:none;stroke:var(--color-gold);stroke-width:8.33px;"/>
#                <path d="M1126.07,285.909l-52.693,92.696l109.369,0.072l-56.676,-92.768Z" style="stroke:var(--color-gold);stroke-width:2.08px;"/>
#                <path d="M1879.93,1123.96l82.437,-0" style="fill:none;stroke:var(--color-gold);stroke-width:16.67px;"/>
#                <path d="M1125.38,1964.09l-0,-82.703" style="fill:none;stroke:var(--color-gold);stroke-width:16.67px;"/>
#              </g>
#              <g id="NESW">
#                <g transform="matrix(191.667,0,0,191.667,1210.38,560.357)"></g>
#                  <text x="1055.51px" y="560.357px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">N</text>
#                <g transform="matrix(191.667,0,0,191.667,1832.45,1188.08)"></g>
#                  <text x="1703.84px" y="1188.09px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">E</text>
#                <g transform="matrix(191.667,0,0,191.667,1192.38,1809.29)"></g>
#                  <text x="1070.1px" y="1809.3px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">S</text>
#                <g transform="matrix(191.667,0,0,191.667,630.031,1188.08)"></g>
#                  <text x="407.123px" y="1188.09px" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:191.667px;fill:var(--color-gold);">W</text>
#              </g>
#              <g id="Bearing" transform="rotate(` + bearing + ` 1125 1125)">
#                <g><path d="M1137.54,340.861l0.146,294.307l-24.794,1.592c-0,0 -2.052,-246.606 -2.463,-295.928c0,0 0.122,0.2 0,0" style="fill:var(--color-gold);stroke-width:2.08px;" />
#                  <path d="M1156.99,330.877c-25.849,18.327 -61.714,12.22 -80.041,-13.629c-18.327,-25.849 -12.22,-61.714 13.63,-80.041c25.849,-18.327 61.714,-12.219 80.04,13.63c18.327,25.849 12.22,61.714 -13.629,80.04Zm-16.603,-23.417c-12.925,9.163 -30.857,6.11 -40.02,-6.815c-9.164,-12.924 -6.11,-30.857 6.814,-40.02c12.925,-9.164 30.857,-6.11 40.021,6.814c9.163,12.925 6.109,30.858 -6.815,40.021Z" style="fill:var(--color-gold);stroke-width:2.27px;"/>
#                </g>
#                  <path d="M1124.83,1985.4l69.828,-147.314l-55.777,34.667l-3.626,-295.232l-25.323,0.2l-1.847,291.762l-52.894,-24.77l69.639,140.687Z" style="fill:var(--color-gold);stroke-width:2.08px;"/>
#                    <animateTransform additive="sum" attributeName="transform" calcMode="spline" dur="2s" keySplines=".42, 0, .58, 1; .42, 0, .58, 1" repeatCount="indefinite" type="rotate" values="0 1125 1125; 5 1125 1125; 0 1125 1125" />    
#                </g>
#              <g id="Cardinal" ></g>
#                <text x="57%" y="57%" dominant-baseline="middle" text-anchor="middle" style="font-family:'Montserrat-Bold', 'Montserrat';font-weight:700;font-size:250px;">`+ cardinal + `</tspan></text>
#            </g>
#          </svg>
#        `;
#      ]]]

```
![grafik](https://github.com/user-attachments/assets/dace379a-c850-4f4d-be9d-b92847f1c895)
