### ISSUE TITLE
Config.Yaml Code doesn´t work!

### ISSUE THREAD

**Issue by fanqyxl** [damianeickhoff/HaCasa#19]
So I am going through the config.yaml documentation and I am pasting this:

`lovelace:
  mode: "storage"
  resources:
    - url: "/hacsfiles/button-card/button-card.js"
      type: "module"
    - url: "/hacsfiles/my-cards/my-cards.js"
      type: "module"
    - url: "/hacsfiles/kiosk-mode/kiosk-mode.js"
      type: module
    - url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900"
      type: css
  dashboards:
    HaCasa:
      mode: "yaml"
      title: HaCasa
      icon: mdi:script
      show_in_sidebar: true
      filename: "dashboard/HaCasa/main.yaml"`

But I get this error: 

Configuration errors
Invalid config for 'lovelace' at configuration.yaml, line 26: Url path needs to contain a hyphen (-) for dictionary value 'lovelace->dashboards', got {'HaCasa': {'mode': 'yaml', 'title': 'HaCasa', 'icon': 'mdi:script', 'show_in_sidebar': True, 'filename': 'dashboard/HaCasa/main.yaml'}}

I am pasting as is with no changes.

Help?

**Comment by damianeickhoff** [comment]
Make sure it looks like this:
![image](https://github.com/damianeickhoff/HaCasa/assets/12126826/a6e6acc6-19e8-499a-b79b-44ae146cd304)

**Comment by mariosemes** [comment]
I can confirm the same issue but this fixed it:
Changing the original dashboard name frome **HaCasa:** to **mini-hass:**

Now configuration is checked successfully

**Comment by damianeickhoff** [comment]
@mariosemes that is weird! I was almost certain I changed it all to HaCasa. Can you tell me where you changed this exactly?

**Comment by BerrisNO** [comment]
I had the same issue, but changed the name in configuration.yaml: 

`dashboards:
    mini-hass:
      mode: "yaml"
      title: HaCasa
      icon: fapro:house
      show_in_sidebar: true
      filename: "dashboard/HaCasa/main.yaml"`

**Comment by hAMMERlized** [comment]
Can confirm, issue is still available. Changing to "mini-hass" fixed the problem.

**Comment by gshel** [comment]
```
lovelace:
  mode: "storage"
  resources:
    - url: "/hacsfiles/button-card/button-card.js"
      type: "module"
    - url: "/hacsfiles/my-cards/my-cards.js"
      type: "module"
    - url: "/hacsfiles/kiosk-mode/kiosk-mode.js"
      type: module
  dashboards:
    mini-hass: # Change this line from `HaCasa` -> `mini-hass`
      mode: "yaml"
      title: HaCasa
      icon: mdi:script
      show_in_sidebar: true
      filename: "dashboard/HaCasa/main.yaml"
```
