### ISSUE TITLE
Weather forecast animated icons doens't work

### ISSUE THREAD

**Issue by RemcoveHA** [damianeickhoff/HaCasa#25]
Hello, 

Can you please provide the animated weather accounts and how to install them? I see in the code that the weather card depends on them for the icon to work however they are not provided.

Also Home assistant changed the way it deals with weather forecast data. See: https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

Maybe add instructions on how to make it work? I figured it out by extensive google. Just an suggestion :).

Kind regards,
Remco

**Comment by Scatman007** [comment]
> Hello,
> 
> Can you please provide the animated weather accounts and how to install them? I see in the code that the weather card depends on them for the icon to work however they are not provided.
> 
> Also Home assistant changed the way it deals with weather forecast data. See: https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service
> 
> Maybe add instructions on how to make it work? I figured it out by extensive google. Just an suggestion :).
> 
> Kind regards, Remco

Can you share the config? I've been trying forever and can't get the weather to work.

**Comment by RemcoveHA** [comment]
What part doens't work for you? The weather card itself or the animated icons?

**Comment by Scatman007** [comment]
> What part doens't work for you? The weather card itself or the animated icons?

the whole weather card  :-)
Can't figure out how to do the entities/sensors. Tried some different things I found on the internet, but no luck.
I guess they are all related to the buienradar plugin?

**Comment by stijn2911** [comment]
> > What part doens't work for you? The weather card itself or the animated icons?
> 
> the whole weather card :-) Can't figure out how to do the entities/sensors. Tried some different things I found on the internet, but no luck. I guess they are all related to the buienradar plugin?

I finally got it to work after a lot of googling

Weather config in /dashboards/HaCasa/views/00-default_view.yaml:
```yml
      - type: custom:button-card
        template:
          - custom_card_weather_forecast
        name: "[[[ return states['sensor.temperature'].state + ' °C']]]"
        entity: weather.buienradar
        tap_action:
          action: navigate
          navigation_path: "weather"
```

Weather Forecast config in /dashboards/HaCasa/templates/custom_card_weather/custom_card_weather_forecast.yaml:
```yml
custom_card_weather_forecast:
  show_state: false
  show_icon: false
  variables:
    hc_enable_forecast: true
  styles:
    grid:
      - grid-template-areas: >
          [[[
            if (variables.hc_enable_forecast) {
              return '"weather_info n" "weather_states weather_states"';
            }
            return 'weather_info n';
          ]]]
      - row-gap: 3rem
    card:
      - background: var(--color-dark-blue)
      - padding: 15px
    name:
      - font-size: 2.5rem
      - color: var(--color-white)
      - align-self: start
      - margin-right: 20px
      - padding-top: 0.5rem
    custom_fields:
      weather_info:
        - justify-self: start
        - align-self: start
        - margin-top: "-20px"
  custom_fields:
    weather_info:
      card:
        type: custom:button-card
        entity: weather.buienradar
        show_state: false
        show_icon: false
        show_label: true
        label: '[[[ return states["sensor.precipitation_forecast_total"].state + " mm"]]]'
        name: "[[[ return states[entity.entity_id].state ]]]"
        styles:
          grid:
            - grid-template-areas: "'icon n''icon l'"
          card:
            - background: none
            - padding: 0
            - height: 60px
            - border-radius: 0
            - overflow: visible
            - box-shadow: none
          name:
            - justify-self: start
            - align-self: end
            - color: var(--color-white)
            - font-family: montserrat
            - font-weight: 600
            - font-size: 1.1rem
          label:
            - justify-self: start
            - color: var(--color-dark-gray)
            - font-family: montserrat
            - font-weight: 500
            - font-size: 1rem
          custom_fields:
            icon:
              - width: 7rem
              - height: 7rem
        custom_fields:
          icon: |
            [[[
                var weather = states[entity.entity_id].state;
                return '<img src = "/local/weather-icons/' + weather + '.svg" />'
            ]]]
    weather_states:
      card:
        type: custom:button-card
        entity: weather.buienradar
        show_name: false
        show_icon: false
        styles:
          grid:
            - grid-template-areas: '"item1 item2 item3 item4 item5"'
            - grid-template-columns: 1fr 1fr 1fr 1fr 1fr
          card:
            - background: none
            - box-shadow: none
            - padding: 0
        custom_fields:
          item1:
            card:
              type: custom:button-card
              entity: "[[[ return entity.entity_id ]]]"
              label: >-
                [[[ return states["sensor.temperature_1d"].state + "<span style>°C</span>" ]]]
              name: '[[[ return states["sensor.condition_1d"].state ]]]'
              show_label: true
              show_icon: false
              styles: &item_styles
                grid:
                  - grid-template-areas: '"l l" "icon icon" "n n"'
                  - grid-template-rows: min-content
                card:
                  - background: none
                  - padding: 0
                  - box-shadow: none
                name:
                  - font-weight: 400
                  - opacity: 0.8
                  - font-size: 1rem
                  - color: var(--color-white)
                label:
                  - font-size: 1rem
                  - font-weight: 600
                  - color: var(--color-white)
                custom_fields:
                  icon:
                    - width: 50px
                    - justify-self: center
                  rain:
                    - color: white
                    - font-size: 1rem
              custom_fields:
                icon: |
                  [[[
                      var weather = states["sensor.condition_1d"].state;
                      return '<img src = "/local/weather-icons/' + weather + '.svg" />'
                  ]]]
          item2:
            card:
              type: custom:button-card
              entity: "[[[ return entity.entity_id ]]]"
              label: >-
                [[[ return
                states["sensor.temperature_2d"].state + " °C"]]]
              name: '[[[ return states["sensor.condition_2d"].state ]]]'
              show_label: true
              show_icon: false
              custom_fields:
                icon: |
                  [[[
                      var weather = states[ "sensor.condition_2d"].state;
                      return '<img src = "/local/weather-icons/' + weather + '.svg" />'
                  ]]]
              styles: *item_styles
          item3:
            card:
              type: custom:button-card
              entity: "[[[ return entity.entity_id ]]]"
              label: >-
                [[[ return states["sensor.temperature_3d"].state + " °C" ]]]
              name: '[[[ return states["sensor.condition_3d"].state ]]]'
              show_label: true
              show_icon: false
              custom_fields:
                icon: |
                  [[[
                      var weather = states["sensor.condition_3d"].state;
                      return '<img src = "/local/weather-icons/' + weather + '.svg" />'
                  ]]]
              styles: *item_styles
          item4:
            card:
              type: custom:button-card
              entity: "[[[ return entity.entity_id ]]]"
              label: >-
                [[[ return states["sensor.temperature_4d"].state + " °C" ]]]
              name: '[[[ return states["sensor.condition_4d"].state ]]]'
              show_label: true
              show_icon: false
              custom_fields:
                icon: |
                  [[[
                      var weather = states["sensor.condition_4d"].state;
                      return '<img src = "/local/weather-icons/' + weather + '.svg" />'
                  ]]]
              styles: *item_styles
          item5:
            card:
              type: custom:button-card
              entity: "[[[ return entity.entity_id ]]]"
              label: >-
                [[[ return states["sensor.temperature_5d"].state + " °C" ]]]
              name: '[[[ return states["sensor.condition_5d"].state ]]]'
              show_label: true
              show_icon: false
              custom_fields:
                icon: |
                  [[[
                      var weather = states["sensor.condition_5d"].state;
                      return '<img src = "/local/weather-icons/' + weather + '.svg" />'
                  ]]]
              styles: *item_styles
```

You must also enable the necessary sensors in the Buienradar integration, since they are disabled by default. 
Now, only the icons aren't working for me. I guess I'll have to find another .svg weather set and place them under /www/weather-icons? Or does anyone have the animated icons?
