### ISSUE TITLE
Broken Theme

### ISSUE THREAD

**Issue by HeyItsJono** [damianeickhoff/HaCasa#30]
Hey there, this is the first time I've installed a HA theme so I may have done something wrong, but I've followed the install instructions to a tee and yet the HaCasa example dashboard is broken when I try to view it:
![image](https://github.com/user-attachments/assets/ba175138-a56f-4a4c-9bcf-308a6349c153)

I made a backup, installed the 5 prerequisite dependencies via HACS, copied the dashboard & custom_icons folders to my HA root, made a themes folder there and copied the HaCasa folder across into it, put the weather-icons in the appropriate subfolder under www, added the HaCasa code to my config.yaml, and enabled the theme in my Profile.

My config looks like this:
```
# Enable custom theme support
frontend:
  themes: !include_dir_merge_named themes

#### HaCasa Theme ####
lovelace:
  mode: "storage"
  resources:
    - url: "/hacsfiles/button-card/button-card.js"
      type: "module"
    - url: "/hacsfiles/my-cards/my-cards.js"
      type: "module"
    - url: "/hacsfiles/kiosk-mode/kiosk-mode.js"
      type: module
    - url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900"
      type: css
  dashboards:
    hacasa-dashboard:
      mode: "yaml"
      title: HaCasa
      icon: mdi:script
      show_in_sidebar: true
      filename: "dashboard/HaCasa/main.yaml"
#######################
```

The theme looks quite pretty, I'd love some help in getting it running if you can spare some time :)
