### ISSUE TITLE
Switch card does not show power

### ISSUE THREAD

**Issue by ewnhof** [damianeickhoff/HaCasa#64]
Hi,

I use smart switches via the Tuya integration, which expose their power consumption as `sensor.<name>_power`. The sensor works, however the power is not displayed in the card.

The code for the card:

```yaml
          - type: custom:button-card
            template: hc_switch_card
            entity: switch.monitor
            variables:
              - power_entity: sensor.monitor_power
              - show_graph: True
```

I'm pretty new to this and don't know how to debug this, but let me know if I can help in any way.

**Comment by damianeickhoff** [comment]
He @ewnhof , maybe you fixed it already, but you should remove the `-`.

```yaml
- type: custom:button-card
  template: hc_switch_card
  entity: switch.monitor
  variables:
    power_entity: sensor.monitor_power
    show_graph: True
```
